DROP DATABASE IF EXISTS TEST;
CREATE DATABASE TEST;

use TEST;

DROP TABLE IF EXISTS Student_details;

CREATE TABLE Student_details(
   ID   INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(20) NOT NULL,
   AGE  INT NOT NULL,
   PRIMARY KEY (ID)
);